export const dark = {
  fontFamily: {
    primary: "Gilroy",
  },
  letterSpacing: {
    default: "1px",
  },
  iconSize: {
    height: "1.875rem",
    width: "1.875rem",
  },
  inputSize: {
    height: "2.813rem",
    width: "25rem",
  },
  colors: {
    background: "#080808",
    secondary: "#0f0f0f",
    textColor: "#ffffff",
    backgroundItems: "#1c1c1c",
    sideBarIconsActive: "#fffffd",
    sideBarIconsNoActive: "#838383",
    sideBarTextActive: "#fffffd",
    sideBarTextNoActive: "#838383",
    red: "#ae5467",
    lightGrey: "#383838",
    buttonColor: "#e36d85",
    hoverButton: "#ae5467",
    userMenuBackground: "#838383",
  },
  boxShadow: {
    primary: "rgba(0, 0, 0, 0.24) 0px 3px 8px",
    secondary: "rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px",
  },
  graphColors: ["#29a5e9", "#ffffff", "#ae5467"],
  bold_24px: {
    fontFamily: "Gilroy",
    fontWeight: "bold",
    fontStyle: "normal",
    fontSize: "1.5rem",
    color: "#ffffff",
    letterSpacing: "1px",
  },
  bold_16px: {
    fontFamily: "Gilroy",
    fontWeight: "bold",
    fontStyle: "normal",
    fontSize: "1rem",
    color: "#ffffff",
    letterSpacing: "1px",
  },
  normal_18px: {
    fontFamily: "Gilroy",
    fontWeight: "normal",
    fontStyle: "normal",
    fontSize: "1.125rem",
    color: "#ffffff",
    letterSpacing: "1px",
  },
  normal_16px: {
    fontFamily: "Gilroy",
    fontWeight: "normal",
    fontStyle: "normal",
    fontSize: "1rem",
    color: "#ffffff",
    letterSpacing: "1px",
  },
  normal_14px: {
    fontFamily: "Gilroy",
    fontWeight: "normal",
    fontStyle: "normal",
    fontSize: "0.875rem",
    color: "#ffffff",
    letterSpacing: "1px",
  },
  sidebar_active_text: {
    fontFamily: "Gilroy",
    fontWeight: "bold",
    fontStyle: "normal",
    fontSize: "1rem",
    color: "#fffffd",
    letterSpacing: "1px",
    textTransform: "capitalize",
    userSelect: "none",
  },
  sidebar_inactive_text: {
    fontFamily: "Gilroy",
    fontWeight: "bold",
    fontStyle: "normal",
    fontSize: "1rem",
    color: "#838383",
    letterSpacing: "1px",
    textTransform: "capitalize",
    userSelect: "none",
  },
};

export const light = {
  fontFamily: {
    primary: "Gilroy",
  },
  letterSpacing: {
    default: "1px",
  },
  iconSize: {
    height: "1.875rem",
    width: "1.875rem",
  },
  inputSize: {
    height: "2.813rem",
    width: "25rem",
  },
  colors: {
    background: "#fffffd",
    secondary: "#a49df1",
    textColor: "#080808",
    backgroundItems: "#d7dffd",
    sideBarIconsActive: "#fffffd",
    sideBarIconsNoActive: "#838383",
    sideBarTextActive: "#fffffd",
    sideBarTextNoActive: "#838383",
    buttonColor: "#7957c0",
    red: "#ae5467",
    lightGrey: "#383838",
    hoverButton: "#ae5467",
    userMenuBackground: "#838383",
  },
  boxShadow: {
    primary: "rgba(0, 0, 0, 0.24) 0px 3px 8px",
    secondary: "rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px",
  },
  graphColors: ["#29a5e9", "#080808", "#ae5467"],
  bold_24px: {
    fontFamily: "Gilroy",
    fontWeight: "bold",
    fontStyle: "normal",
    fontSize: "1.5rem",
    color: "#080808",
    letterSpacing: "1px",
  },
  bold_16px: {
    fontFamily: "Gilroy",
    fontWeight: "bold",
    fontStyle: "normal",
    fontSize: "1rem",
    color: "#080808",
    letterSpacing: "1px",
  },
  normal_18px: {
    fontFamily: "Gilroy",
    fontWeight: "normal",
    fontStyle: "normal",
    fontSize: "1.125rem",
    color: "#080808",
    letterSpacing: "1px",
  },
  normal_16px: {
    fontFamily: "Gilroy",
    fontWeight: "normal",
    fontStyle: "normal",
    fontSize: "1rem",
    color: "#080808",
    letterSpacing: "1px",
  },
  normal_14px: {
    fontFamily: "Gilroy",
    fontWeight: "normal",
    fontStyle: "normal",
    fontSize: "0.875rem",
    color: "#080808",
    letterSpacing: "1px",
  },
  sidebar_active_text: {
    fontFamily: "Gilroy",
    fontWeight: "bold",
    fontStyle: "normal",
    fontSize: "1rem",
    color: "#fffffd",
    letterSpacing: "1px",
    textTransform: "capitalize",
    userSelect: "none",
  },
  sidebar_inactive_text: {
    fontFamily: "Gilroy",
    fontWeight: "bold",
    fontStyle: "normal",
    fontSize: "1rem",
    color: "#838383",
    letterSpacing: "1px",
    textTransform: "capitalize",
    userSelect: "none",
  },
  user_name_tag: {
    fontFamily: "Gilroy",
    fontWeight: "bold",
    fontStyle: "normal",
    fontSize: "1.5rem",
    color: "#fffffd",
    userSelect: "none",
  },
};
